(() => {
  const game=document.getElementById('game'), ctx=game.getContext('2d');
  const map=document.getElementById('map'), mctx=map.getContext('2d');
  const stage=document.getElementById('stage'), overlay=document.getElementById('overlay');
  const timerEl=document.getElementById('timer'), hud=document.getElementById('hud');

  const COLORS=[
    {name:'Ruby',color:'#ff3b5c'},
    {name:'Azure',color:'#3ea0ff'},
    {name:'Lime',color:'#70e35a'},
    {name:'Gold',color:'#ffd23f'}
  ];

  const TRACK_HALF=92, R=17;
  const GRAVITY=235, AIR_DRAG=0.20;
  const WALL_RESTITUTION=0.67, BALL_RESTITUTION=0.91, PEG_RESTITUTION=0.82;
  const STALL_SECONDS=8, RACE_CAP=50;

  const COURSES=[
    {name:'Rolling Hills',blurb:'Wide flowing bends • Peg field • 1 funnel',points:[[220,160],[250,560],[420,980],[760,1120],[1050,920],[1110,570],[940,280],[1280,180],[1580,470],[1500,920]],pegs:[.20,.48,.72],funnels:[.61]},
    {name:'Hairpin Valley',blurb:'Long natural switchbacks • 2 funnels',points:[[210,170],[230,690],[420,1110],[790,1190],[1030,990],[970,650],[690,430],[760,190],[1160,160],[1450,390],[1570,780],[1430,1120]],pegs:[.18,.42,.76],funnels:[.31,.66]},
    {name:'Twister Run',blurb:'S-bends • Dense peg sections • 2 funnels',points:[[230,170],[360,470],[700,620],[980,470],[1160,210],[1450,330],[1510,690],[1260,930],[900,1040],[570,900],[420,1160],[850,1290],[1330,1190],[1580,980]],pegs:[.16,.29,.52,.82],funnels:[.40,.69]},
    {name:'Grand Descent',blurb:'Fast sweepers • Sparse obstacles • 1 large funnel',points:[[180,160],[310,430],[560,670],[850,770],[1140,690],[1430,430],[1600,620],[1490,970],[1170,1140],[780,1130],[450,970],[300,1210]],pegs:[.25,.78],funnels:[.55],funnelSize:1.18},
    {name:'Chaos Circuit',blurb:'Tighter bends • Heavy traffic • 3 funnels',points:[[220,160],[260,460],[530,650],[830,560],[980,300],[1280,230],[1530,450],[1450,730],[1160,840],[940,1060],[630,1150],[390,990],[530,780],[890,760],[1210,980],[1510,1170]],pegs:[.12,.24,.46,.58,.86],funnels:[.34,.67,.79]}
  ];

  let W=0,H=0,DPR=1,MW=0,MH=0,MDPR=1;
  let path=[],totalLength=0,walls=[],pegs=[],funnels=[],bounds={minX:0,minY:0,maxX:1,maxY:1};
  let marbles=[],finishOrder=[],selectedCourse=0;
  let state='idle',startTime=0,lastTime=0,raf=0,raceToken=0;
  let camX=0,camY=0,camAngle=0,camS=0,camLeaderId=0;
  let audioCtx=null,lastClink=new Map();

  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const rnd=(a,b)=>a+Math.random()*(b-a);

  function catmull(p0,p1,p2,p3,t){const t2=t*t,t3=t2*t;return{x:.5*((2*p1[0])+(-p0[0]+p2[0])*t+(2*p0[0]-5*p1[0]+4*p2[0]-p3[0])*t2+(-p0[0]+3*p1[0]-3*p2[0]+p3[0])*t3),y:.5*((2*p1[1])+(-p0[1]+p2[1])*t+(2*p0[1]-5*p1[1]+4*p2[1]-p3[1])*t2+(-p0[1]+3*p1[1]-3*p2[1]+p3[1])*t3)}}
  function buildPath(control){const raw=[];for(let i=0;i<control.length-1;i++){const p0=control[Math.max(0,i-1)],p1=control[i],p2=control[i+1],p3=control[Math.min(control.length-1,i+2)],dist=Math.hypot(p2[0]-p1[0],p2[1]-p1[1]),n=Math.max(10,Math.ceil(dist/24));for(let j=0;j<n;j++)raw.push(catmull(p0,p1,p2,p3,j/n))}raw.push({x:control.at(-1)[0],y:control.at(-1)[1]});path=[];let s=0;raw.forEach((p,i)=>{if(i)s+=Math.hypot(p.x-raw[i-1].x,p.y-raw[i-1].y);path.push({x:p.x,y:p.y,s})});totalLength=s}
  function pointAtS(s){s=clamp(s,0,totalLength);let lo=1;while(lo<path.length&&path[lo].s<s)lo++;lo=Math.min(lo,path.length-1);const a=path[lo-1],b=path[lo],span=b.s-a.s||1,t=(s-a.s)/span;return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}}
  function smoothTangentAtS(s,span=105){const a=pointAtS(clamp(s-span,0,totalLength)),b=pointAtS(clamp(s+span,0,totalLength)),dx=b.x-a.x,dy=b.y-a.y,L=Math.hypot(dx,dy)||1;return{x:dx/L,y:dy/L}}
  function tangentAtIndex(i){const a=path[Math.max(0,i-3)],b=path[Math.min(path.length-1,i+3)],dx=b.x-a.x,dy=b.y-a.y,L=Math.hypot(dx,dy)||1;return{x:dx/L,y:dy/L}}

  function buildCourse(){const c=COURSES[selectedCourse];buildPath(c.points);walls=[];pegs=[];funnels=[];const left=[],right=[];for(let i=0;i<path.length;i++){const t=tangentAtIndex(i),nx=-t.y,ny=t.x;left.push({x:path[i].x+nx*TRACK_HALF,y:path[i].y+ny*TRACK_HALF});right.push({x:path[i].x-nx*TRACK_HALF,y:path[i].y-ny*TRACK_HALF})}for(let i=1;i<path.length;i++){walls.push({a:left[i-1],b:left[i],s0:path[i-1].s,s1:path[i].s});walls.push({a:right[i-1],b:right[i],s0:path[i-1].s,s1:path[i].s})}c.pegs.forEach((frac,k)=>{const s=totalLength*frac,q=pointAtS(s),t=smoothTangentAtS(s,45),nx=-t.y,ny=t.x;if(k%2===0){pegs.push({x:q.x+nx*35,y:q.y+ny*35,r:21,s});pegs.push({x:q.x-nx*42+t.x*54,y:q.y-ny*42+t.y*54,r:21,s:s+54})}else pegs.push({x:q.x,y:q.y,r:28,s})});c.funnels.forEach((frac,i)=>{const s=totalLength*frac,q=pointAtS(s),t=smoothTangentAtS(s,60),nx=-t.y,ny=t.x,scale=(c.funnelSize||1);funnels.push({id:i,s,x:q.x,y:q.y,outerR:118*scale,holeR:22*scale,entrySide:i%2?-1:1,tx:t.x,ty:t.y,nx,ny})});const xs=path.map(p=>p.x),ys=path.map(p=>p.y);bounds={minX:Math.min(...xs)-150,maxX:Math.max(...xs)+150,minY:Math.min(...ys)-150,maxY:Math.max(...ys)+150}}

  function nearestTrack(m){const start=Math.max(0,(m.segIndex||0)-20),end=Math.min(path.length-2,(m.segIndex||0)+28);let best={d2:Infinity,index:m.segIndex||0,s:m.progress||0,x:path[0].x,y:path[0].y};for(let i=start;i<=end;i++){const a=path[i],b=path[i+1],abx=b.x-a.x,aby=b.y-a.y,den=abx*abx+aby*aby||1,tt=clamp(((m.x-a.x)*abx+(m.y-a.y)*aby)/den,0,1),x=a.x+abx*tt,y=a.y+aby*tt,dx=m.x-x,dy=m.y-y,d2=dx*dx+dy*dy;if(d2<best.d2)best={d2,index:i,x,y,s:a.s+(b.s-a.s)*tt}}m.segIndex=best.index;m.progress=best.s;return best}
  function closestPointOnSegment(px,py,ax,ay,bx,by){const abx=bx-ax,aby=by-ay,den=abx*abx+aby*aby||1,tt=clamp(((px-ax)*abx+(py-ay)*aby)/den,0,1);return{x:ax+abx*tt,y:ay+aby*tt}}
  function collideWall(m,w){if(m.funnel||Math.abs(((w.s0+w.s1)/2)-m.progress)>310)return;const q=closestPointOnSegment(m.x,m.y,w.a.x,w.a.y,w.b.x,w.b.y);let dx=m.x-q.x,dy=m.y-q.y,d=Math.hypot(dx,dy);if(d>=R)return;if(d<.001){const sx=w.b.x-w.a.x,sy=w.b.y-w.a.y;dx=-sy;dy=sx;d=Math.hypot(dx,dy)||1}const nx=dx/d,ny=dy/d,pen=R-d;m.x+=nx*(pen+.2);m.y+=ny*(pen+.2);const vn=m.vx*nx+m.vy*ny;if(vn<0){m.vx-=(1+WALL_RESTITUTION)*vn*nx;m.vy-=(1+WALL_RESTITUTION)*vn*ny}}
  function collidePeg(m,p){if(m.funnel||Math.abs(p.s-m.progress)>230)return;let dx=m.x-p.x,dy=m.y-p.y,d=Math.hypot(dx,dy),minD=R+p.r;if(d>=minD)return;if(d<.001){dx=1;dy=0;d=1}const nx=dx/d,ny=dy/d,pen=minD-d;m.x+=nx*(pen+.2);m.y+=ny*(pen+.2);const vn=m.vx*nx+m.vy*ny;if(vn<0){m.vx-=(1+PEG_RESTITUTION)*vn*nx;m.vy-=(1+PEG_RESTITUTION)*vn*ny}}

  function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
  function playClink(impact,pairKey){if(!audioCtx)return;const now=audioCtx.currentTime,last=lastClink.get(pairKey)||-1;if(now-last<.055)return;lastClink.set(pairKey,now);const gain=audioCtx.createGain(),o1=audioCtx.createOscillator(),o2=audioCtx.createOscillator(),vol=clamp(impact/420,.015,.085);gain.gain.setValueAtTime(vol,now);gain.gain.exponentialRampToValueAtTime(.0001,now+.055);o1.type='sine';o2.type='sine';o1.frequency.setValueAtTime(1450+rnd(-130,130),now);o2.frequency.setValueAtTime(2350+rnd(-180,180),now);o1.frequency.exponentialRampToValueAtTime(1150,now+.05);o2.frequency.exponentialRampToValueAtTime(1850,now+.045);o1.connect(gain);o2.connect(gain);gain.connect(audioCtx.destination);o1.start(now);o2.start(now);o1.stop(now+.06);o2.stop(now+.055)}
  function collideBalls(a,b){if(a.funnel||b.funnel||Math.abs(a.progress-b.progress)>120)return;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>=R*2)return;if(d<.001){dx=1;dy=0;d=1}const nx=dx/d,ny=dy/d,pen=R*2-d;a.x-=nx*pen*.5;a.y-=ny*pen*.5;b.x+=nx*pen*.5;b.y+=ny*pen*.5;const rvx=b.vx-a.vx,rvy=b.vy-a.vy,rel=rvx*nx+rvy*ny;if(rel>=0)return;const impact=-rel,j=-(1+BALL_RESTITUTION)*rel/2;a.vx-=j*nx;a.vy-=j*ny;b.vx+=j*nx;b.vy+=j*ny;playClink(impact,[a.id,b.id].sort().join('-'))}

  function maybeEnterFunnel(m){if(m.funnel||m.finished)return;for(const f of funnels){if(m.usedFunnels.has(f.id)||Math.abs(m.progress-f.s)>90)continue;if(m.progress>=f.s-48){const speed=Math.max(150,Math.hypot(m.vx,m.vy)),side=f.entrySide;m.funnel={id:f.id,f,theta:side>0?Math.atan2(f.ny,f.nx):Math.atan2(-f.ny,-f.nx)};m.x=f.x+f.nx*f.outerR*side;m.y=f.y+f.ny*f.outerR*side;const sign=side>0?-1:1;m.vx=-Math.sin(m.funnel.theta)*speed*sign;m.vy=Math.cos(m.funnel.theta)*speed*sign;return}}}
  function updateFunnel(m,dt){const fs=m.funnel,f=fs.f;let dx=m.x-f.x,dy=m.y-f.y,d=Math.hypot(dx,dy)||1,rx=dx/d,ry=dy/d;const bowlG=390;m.vx+=-rx*bowlG*dt;m.vy+=-ry*bowlG*dt;const damping=Math.exp(-.42*dt);m.vx*=damping;m.vy*=damping;m.x+=m.vx*dt;m.y+=m.vy*dt;dx=m.x-f.x;dy=m.y-f.y;d=Math.hypot(dx,dy)||1;if(d>f.outerR-R){const nx=dx/d,ny=dy/d,pen=d-(f.outerR-R);m.x-=nx*pen;m.y-=ny*pen;const vn=m.vx*nx+m.vy*ny;if(vn>0){m.vx-=1.55*vn*nx;m.vy-=1.55*vn*ny}}m.progress=f.s+clamp((f.outerR-d)/f.outerR,0,1)*85;if(d<f.holeR+R*.35){const exitS=Math.min(totalLength-30,f.s+125),q=pointAtS(exitS),t=smoothTangentAtS(exitS,55),exitSpeed=Math.max(185,Math.hypot(m.vx,m.vy)*.82);m.x=q.x;m.y=q.y;m.vx=t.x*exitSpeed;m.vy=t.y*exitSpeed;m.progress=exitS;m.usedFunnels.add(f.id);m.funnel=null;nearestTrack(m)}}

  function physicsStep(dt,elapsed){const damping=Math.exp(-AIR_DRAG*dt);for(const m of marbles){if(m.finished)continue;if(m.funnel)updateFunnel(m,dt);else{const near=nearestTrack(m),t=tangentAtIndex(near.index);m.vx+=t.x*GRAVITY*dt;m.vy+=t.y*GRAVITY*dt;m.vx*=damping;m.vy*=damping;m.x+=m.vx*dt;m.y+=m.vy*dt;nearestTrack(m);for(let pass=0;pass<2;pass++){for(const w of walls)collideWall(m,w);for(const p of pegs)collidePeg(m,p)}nearestTrack(m);maybeEnterFunnel(m)}const speed=Math.hypot(m.vx,m.vy);m.omega+=(speed/R-m.omega)*Math.min(1,dt*5);m.angle+=m.omega*dt}for(let pass=0;pass<2;pass++)for(let i=0;i<marbles.length;i++)for(let j=i+1;j<marbles.length;j++)if(!marbles[i].finished&&!marbles[j].finished)collideBalls(marbles[i],marbles[j]);for(let i=0;i<marbles.length;i++){const m=marbles[i];if(m.finished)continue;if(m.progress>=totalLength-55){m.finished=true;m.finishTime=elapsed;finishOrder.push(i);continue}if(m.progress>m.lastProgress+34){m.lastProgress=m.progress;m.lastProgressAt=elapsed}else if(elapsed-m.lastProgressAt>STALL_SECONDS&&Math.hypot(m.vx,m.vy)<42&&!m.funnel){m.finished=true;m.dnf=true;m.finishTime=elapsed}if(elapsed>=RACE_CAP&&!m.finished){m.finished=true;m.dnf=true;m.finishTime=elapsed}}const active=marbles.filter(m=>!m.finished).sort((a,b)=>b.progress-a.progress);active.forEach((m,k)=>m.rank=finishOrder.length+k+1);updateHud();if(marbles.every(m=>m.finished))endRace()}

  function currentLeader(){const active=marbles.filter(m=>!m.finished);if(!active.length)return marbles.reduce((a,b)=>b.progress>a.progress?b:a);const actual=active.reduce((a,b)=>b.progress>a.progress?b:a),locked=active.find(m=>m.id===camLeaderId);if(!locked||actual.progress>locked.progress+30)camLeaderId=actual.id;return active.find(m=>m.id===camLeaderId)||actual}
  function updateCamera(){const lead=currentLeader(),focusS=lead.progress,t=smoothTangentAtS(focusS,125),targetAngle=Math.atan2(t.y,t.x),targetX=lead.x-t.x*270,targetY=lead.y-t.y*270;camX+=(targetX-camX)*.035;camY+=(targetY-camY)*.035;let da=((targetAngle-camAngle+Math.PI*3)%(Math.PI*2))-Math.PI;da=clamp(da,-.018,.018);camAngle+=da;camS+=(focusS-camS)*.045}
  function project(x,y){const fx=Math.cos(camAngle),fy=Math.sin(camAngle),rx=-fy,ry=fx,dx=x-camX,dy=y-camY,forward=dx*fx+dy*fy,lateral=dx*rx+dy*ry,view=1030,u=clamp(forward/view,0,1),horizon=H*.18,bottom=H*1.02,sy=bottom-(bottom-horizon)*Math.pow(u,.78),perspective=1.18-.98*Math.pow(u,.88);return{x:W/2+lateral*perspective*(W/760),y:sy,scale:perspective*(W/760),visible:forward>-130&&forward<view+160,forward}}

  function drawCourse(){ctx.clearRect(0,0,W,H);const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#17223e');sky.addColorStop(.55,'#10182d');sky.addColorStop(1,'#070b14');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);updateCamera();const visible=path.filter(p=>p.s>camS-300&&p.s<camS+1250).map(p=>({p,pr:project(p.x,p.y)})).filter(o=>o.pr.visible);if(visible.length>2){const left=[],right=[];visible.forEach(o=>{const t=smoothTangentAtS(o.p.s,55),nx=-t.y,ny=t.x;left.push(project(o.p.x+nx*TRACK_HALF,o.p.y+ny*TRACK_HALF));right.push(project(o.p.x-nx*TRACK_HALF,o.p.y-ny*TRACK_HALF))});ctx.beginPath();ctx.moveTo(left[0].x,left[0].y);left.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));for(let i=right.length-1;i>=0;i--)ctx.lineTo(right[i].x,right[i].y);ctx.closePath();ctx.fillStyle='#283147';ctx.fill();[left,right].forEach(edge=>{ctx.beginPath();ctx.moveTo(edge[0].x,edge[0].y);edge.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.strokeStyle='#98a6bf';ctx.lineWidth=7;ctx.lineJoin='round';ctx.stroke();ctx.strokeStyle='#4c5970';ctx.lineWidth=3;ctx.stroke()})}funnels.forEach(f=>{if(Math.abs(f.s-camS)>1150)return;const p=project(f.x,f.y);if(!p.visible)return;const rr=Math.max(8,f.outerR*p.scale),g=ctx.createRadialGradient(p.x,p.y,rr*.12,p.x,p.y,rr);g.addColorStop(0,'#090c12');g.addColorStop(.18,'#333b4c');g.addColorStop(.72,'#7c879b');g.addColorStop(1,'#b6c0d1');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,rr,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#dbe2ed';ctx.lineWidth=Math.max(2,4*p.scale);ctx.stroke();ctx.fillStyle='#05070b';ctx.beginPath();ctx.arc(p.x,p.y,Math.max(3,f.holeR*p.scale),0,Math.PI*2);ctx.fill()});pegs.forEach(peg=>{if(Math.abs(peg.s-camS)>1100)return;const p=project(peg.x,peg.y);if(!p.visible)return;const rr=Math.max(3,peg.r*p.scale);ctx.fillStyle='#d7a141';ctx.beginPath();ctx.arc(p.x,p.y,rr,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff5';ctx.beginPath();ctx.arc(p.x-rr*.3,p.y-rr*.33,rr*.25,0,Math.PI*2);ctx.fill()});for(let s=Math.ceil((camS-100)/380)*380;s<camS+1150;s+=380){if(s<0||s>totalLength)continue;const q=pointAtS(s),t=smoothTangentAtS(s,70),nx=-t.y,ny=t.x;[-1,1].forEach(side=>{const p=project(q.x+nx*TRACK_HALF*side,q.y+ny*TRACK_HALF*side);if(!p.visible)return;ctx.strokeStyle='#455167';ctx.lineWidth=Math.max(2,6*p.scale);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,p.y+Math.max(18,65*p.scale));ctx.stroke()})}}
  function drawMarble(m){const p=project(m.x,m.y);if(!p.visible)return;const r=Math.max(4,R*p.scale*1.3);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(m.angle);ctx.shadowColor='#000b';ctx.shadowBlur=Math.max(3,r*.45);ctx.shadowOffsetY=Math.max(2,r*.3);const g=ctx.createRadialGradient(-r*.35,-r*.4,2,0,0,r);g.addColorStop(0,'#fff');g.addColorStop(.18,m.color);g.addColorStop(1,'#111');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='#ffffff90';ctx.lineWidth=Math.max(1.5,r*.13);ctx.beginPath();ctx.arc(0,0,r*.6,-1.2,1.15);ctx.stroke();ctx.restore()}
  function drawMinimap(){mctx.clearRect(0,0,MW,MH);mctx.fillStyle='#090e1b';mctx.fillRect(0,0,MW,MH);const bw=bounds.maxX-bounds.minX,bh=bounds.maxY-bounds.minY,scale=Math.min((MW-18)/bw,(MH-18)/bh),ox=(MW-bw*scale)/2-bounds.minX*scale,oy=(MH-bh*scale)/2-bounds.minY*scale;mctx.beginPath();path.forEach((p,i)=>i?mctx.lineTo(ox+p.x*scale,oy+p.y*scale):mctx.moveTo(ox+p.x*scale,oy+p.y*scale));mctx.strokeStyle='#77849e';mctx.lineWidth=Math.max(3,TRACK_HALF*2*scale);mctx.stroke();mctx.strokeStyle='#252d43';mctx.lineWidth=Math.max(2,(TRACK_HALF*2-18)*scale);mctx.stroke();funnels.forEach(f=>{mctx.fillStyle='#bbc6da66';mctx.beginPath();mctx.arc(ox+f.x*scale,oy+f.y*scale,Math.max(3,f.outerR*scale),0,Math.PI*2);mctx.fill()});marbles.forEach(m=>{mctx.fillStyle=m.color;mctx.beginPath();mctx.arc(ox+m.x*scale,oy+m.y*scale,4,0,Math.PI*2);mctx.fill();mctx.strokeStyle='#fff';mctx.lineWidth=1;mctx.stroke()})}

  function makeHud(){hud.innerHTML='';COLORS.forEach((m,i)=>{const row=document.createElement('div');row.className='row';row.innerHTML=`<span class="dot" style="background:${m.color}"></span><span class="name">${m.name}</span><span class="place" id="p${i}">${i+1}</span>`;hud.appendChild(row)})}
  const ordinal=n=>n===1?'1st':n===2?'2nd':n===3?'3rd':'4th';
  function updateHud(){marbles.forEach((m,i)=>{const el=document.getElementById('p'+i),row=el?.closest('.row');if(!el)return;row?.classList.toggle('finished',m.finished&&!m.dnf);row?.classList.toggle('dnf',m.dnf);el.classList.toggle('finished',m.finished&&!m.dnf);el.classList.toggle('dnf',m.dnf);if(m.dnf)el.textContent='DNF';else if(m.finished)el.textContent=`FINISHED • ${ordinal(finishOrder.indexOf(i)+1)}`;else el.textContent=ordinal(m.rank)})}
  function resetMarbles(){finishOrder=[];lastClink.clear();const q=pointAtS(45),t=smoothTangentAtS(45,50),nx=-t.y,ny=t.x;marbles=COLORS.map((m,i)=>({...m,id:i,x:q.x+nx*(i-1.5)*38,y:q.y+ny*(i-1.5)*38,vx:0,vy:0,angle:rnd(0,Math.PI*2),omega:0,finished:false,dnf:false,finishTime:null,rank:i+1,progress:45,segIndex:1,lastProgress:45,lastProgressAt:0,usedFunnels:new Set(),funnel:null}));camLeaderId=0;camX=q.x-t.x*270;camY=q.y-t.y*270;camAngle=Math.atan2(t.y,t.x);camS=45;timerEl.textContent='00.0';updateHud();draw()}
  function resize(){const r=stage.getBoundingClientRect();W=Math.max(320,Math.floor(r.width));H=Math.max(360,Math.floor(r.height));DPR=Math.min(devicePixelRatio||1,2);game.width=W*DPR;game.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0);const mr=map.getBoundingClientRect();MW=Math.max(80,Math.floor(mr.width));MH=Math.max(100,Math.floor(mr.height));MDPR=Math.min(devicePixelRatio||1,2);map.width=MW*MDPR;map.height=MH*MDPR;mctx.setTransform(MDPR,0,0,MDPR,0,0);draw()}
  function draw(){if(!marbles.length)return;drawCourse();[...marbles].sort((a,b)=>a.progress-b.progress).forEach(drawMarble);drawMinimap()}
  function frame(now){if(state!=='racing')return;const elapsed=(now-startTime)/1000;timerEl.textContent=elapsed.toFixed(1).padStart(4,'0');const dt=Math.min(.035,(now-lastTime)/1000||.016);lastTime=now,sub=5,h=dt/sub;for(let i=0;i<sub;i++)physicsStep(h,elapsed);draw();if(state==='racing')raf=requestAnimationFrame(frame)}

  function showStartCard(){overlay.style.display='flex';overlay.innerHTML=`<div class="card courseCard"><h2>Choose a Course</h2><div class="courseGrid">${COURSES.map((c,i)=>`<button class="courseChoice ${i===selectedCourse?'selected':''}" data-course="${i}"><strong>${c.name}</strong><span>${c.blurb}</span></button>`).join('')}</div><button id="startBtn">START RACE</button></div>`;overlay.querySelectorAll('.courseChoice').forEach(btn=>btn.addEventListener('click',()=>{selectedCourse=Number(btn.dataset.course);buildCourse();resetMarbles();showStartCard()}));document.getElementById('startBtn').addEventListener('click',()=>{ensureAudio();startRace()})}
  function resetRace(){raceToken++;cancelAnimationFrame(raf);state='idle';buildCourse();resetMarbles();showStartCard()}
  async function startRace(){if(state==='countdown'||state==='racing')return;ensureAudio();const token=++raceToken;resetMarbles();state='countdown';overlay.style.display='flex';for(let n=3;n>=1;n--){if(token!==raceToken)return;overlay.innerHTML=`<div class="countdown">${n}</div>`;await new Promise(r=>setTimeout(r,650))}if(token!==raceToken)return;overlay.innerHTML='<div class="countdown">GO!</div>';await new Promise(r=>setTimeout(r,380));if(token!==raceToken)return;overlay.style.display='none';state='racing';startTime=performance.now();lastTime=startTime;marbles.forEach(m=>m.lastProgressAt=0);raf=requestAnimationFrame(frame)}
  function endRace(){state='done';cancelAnimationFrame(raf);draw();const winnerIndex=finishOrder[0],winner=winnerIndex!==undefined?marbles[winnerIndex]:null,finalTime=Math.max(...marbles.map(m=>m.finishTime||0)),dnfs=marbles.filter(m=>m.dnf).length;timerEl.textContent=finalTime.toFixed(1);overlay.style.display='flex';overlay.innerHTML=`<div class="card"><h2>${winner?`<span class="winner">${winner.name}</span> Wins!`:'Race Over'}</h2><p>${COURSES[selectedCourse].name}<br>${winner?`Winning time: <strong>${winner.finishTime.toFixed(1)}s</strong><br>`:''}${dnfs?`${dnfs} marble${dnfs===1?'':'s'} recorded a DNF.`:'All four marbles finished.'}</p><button id="againBtn">RACE AGAIN</button></div>`;document.getElementById('againBtn').addEventListener('click',()=>showStartCard())}

  document.getElementById('resetBtn').addEventListener('click',resetRace);
  addEventListener('resize',resize);
  buildCourse();makeHud();resetMarbles();showStartCard();resize();
})();