(() => {
const game=document.getElementById('game'),ctx=game.getContext('2d'),map=document.getElementById('map'),mctx=map.getContext('2d'),stage=document.getElementById('stage'),overlay=document.getElementById('overlay'),timerEl=document.getElementById('timer'),hud=document.getElementById('hud');
const COLORS=[['Ruby','#ff3b5c'],['Azure','#3ea0ff'],['Lime','#70e35a'],['Gold','#ffd23f']];
const TRACK_HALF=88,R=17,GRAVITY=170,AIR=.15,WALL=.72,BALL=.91,PEG=.92,STALL=14;
const COURSES=[
{name:'Rolling Hills',blurb:'Flowing descent • 2 funnels',p:[[220,150],[260,520],[430,920],[760,1160],[1110,1090],[1330,820],[1280,470],[1050,230],[1370,120],[1760,270],[1980,610],[1890,980],[1560,1240],[1190,1370],[820,1260],[520,1040],[310,1270],[430,1620],[810,1780],[1260,1740],[1650,1550],[2070,1650],[2360,1900]],f:[.38,.64],g:[.14,.31,.72,.88]},
{name:'Hairpin Valley',blurb:'Natural switchbacks • 3 funnels',p:[[200,140],[220,620],[390,1060],[720,1280],[1110,1240],[1380,1020],[1420,690],[1210,430],[850,350],[720,110],[1130,90],[1510,250],[1730,590],[1680,940],[1420,1180],[1090,1360],[720,1410],[420,1240],[260,1510],[410,1810],[800,1940],[1220,1870],[1560,1640],[1900,1740],[2210,1980],[2460,1760]],f:[.27,.51,.73],g:[.16,.36,.58,.81]},
{name:'Twister Run',blurb:'Long S-curves • 3 funnels',p:[[220,150],[410,430],[760,580],[1090,470],[1270,190],[1580,180],[1850,390],[1910,720],[1700,990],[1360,1110],[980,1040],[690,850],[420,1050],[390,1390],[650,1620],[1010,1690],[1330,1530],[1610,1320],[1920,1390],[2200,1630],[2350,1940],[2140,2180],[1770,2240],[1420,2100],[1100,2240],[760,2170],[500,1950]],f:[.31,.60,.77],g:[.11,.24,.43,.69,.86]},
{name:'Grand Descent',blurb:'Fast sweepers • 2 large funnels',p:[[180,150],[330,430],[620,650],[960,720],[1290,610],[1580,360],[1890,390],[2100,650],[2050,980],[1770,1230],[1410,1370],[1040,1340],[700,1160],[390,1260],[260,1580],[460,1850],[800,2000],[1190,1980],[1510,1810],[1830,1880],[2140,2090],[2420,1980],[2580,1710],[2500,1430],[2260,1260],[2460,1040],[2700,1170]],f:[.34,.66],g:[.18,.44,.72,.88],fs:1.12},
{name:'Chaos Circuit',blurb:'Technical course • 4 funnels',p:[[220,150],[260,430],[520,620],[850,540],[1010,270],[1320,190],[1590,370],[1570,690],[1300,860],[970,900],[710,1120],[390,1080],[260,1360],[470,1600],[820,1650],[1110,1480],[1370,1290],[1670,1410],[1900,1690],[2210,1760],[2450,1560],[2500,1250],[2260,1060],[1990,1160],[1770,980],[1940,720],[2240,670],[2500,850],[2710,1110],[2820,1430],[2690,1740],[2380,1970],[2030,2070],[1650,2010],[1320,2180],[960,2240],[620,2100]],f:[.25,.43,.68,.82],g:[.10,.20,.47,.62,.76,.90]}
];
let W=0,H=0,MW=0,MH=0,DPR=1,MDPR=1,path=[],L=0,funnels=[],pegs=[],bounds={},balls=[],finish=[],course=0,state='idle',start=0,last=0,raf=0,token=0,camX=0,camY=0,camA=0,camS=0,camH=245,camZ=0,audio=null,lastClink=new Map();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a);
function cat(p0,p1,p2,p3,t){let t2=t*t,t3=t2*t;return{x:.5*((2*p1[0])+(-p0[0]+p2[0])*t+(2*p0[0]-5*p1[0]+4*p2[0]-p3[0])*t2+(-p0[0]+3*p1[0]-3*p2[0]+p3[0])*t3),y:.5*((2*p1[1])+(-p0[1]+p2[1])*t+(2*p0[1]-5*p1[1]+4*p2[1]-p3[1])*t2+(-p0[1]+3*p1[1]-3*p2[1]+p3[1])*t3)}}
function buildPath(c){let raw=[];for(let i=0;i<c.length-1;i++){let p0=c[Math.max(0,i-1)],p1=c[i],p2=c[i+1],p3=c[Math.min(c.length-1,i+2)],n=Math.max(12,Math.ceil(Math.hypot(p2[0]-p1[0],p2[1]-p1[1])/22));for(let j=0;j<n;j++)raw.push(cat(p0,p1,p2,p3,j/n))}raw.push({x:c.at(-1)[0],y:c.at(-1)[1]});path=[];L=0;raw.forEach((p,i)=>{if(i)L+=Math.hypot(p.x-raw[i-1].x,p.y-raw[i-1].y);path.push({x:p.x,y:p.y,s:L})})}
function at(s){s=clamp(s,0,L);let i=1;while(i<path.length&&path[i].s<s)i++;i=Math.min(i,path.length-1);let a=path[i-1],b=path[i],u=(s-a.s)/(b.s-a.s||1);return{x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u}}
function tan(s,d=70){let a=at(s-d),b=at(s+d),x=b.x-a.x,y=b.y-a.y,l=Math.hypot(x,y)||1;return{x:x/l,y:y/l}}
function nearest(b){let best={d:1e99,s:b.s,x:b.x,y:b.y,tx:1,ty:0,nx:0,ny:1},lo=clamp(b.s-420,0,L),hi=clamp(b.s+500,0,L);for(let i=0;i<path.length-1;i++){if(path[i+1].s<lo||path[i].s>hi)continue;let a=path[i],c=path[i+1],dx=c.x-a.x,dy=c.y-a.y,den=dx*dx+dy*dy||1,u=clamp(((b.x-a.x)*dx+(b.y-a.y)*dy)/den,0,1),x=a.x+dx*u,y=a.y+dy*u,ex=b.x-x,ey=b.y-y,dd=ex*ex+ey*ey;if(dd<best.d){let ll=Math.hypot(dx,dy)||1,tx=dx/ll,ty=dy/ll;best={d:dd,s:a.s+(c.s-a.s)*u,x,y,tx,ty,nx:-ty,ny:tx}}}return best}
function zAt(s){let z=0;for(let f of funnels)if(s>=f.exitS)z+=f.depth;return z}
function zBefore(f){let z=0;for(let q of funnels)if(q.exitS<f.exitS)z+=q.depth;return z}
function build(){let c=COURSES[course];buildPath(c.p);funnels=[];pegs=[];c.f.forEach((fr,i)=>{let sc=c.fs||1,mid=L*fr,outer=136*sc,hole=24*sc,depth=88*sc,entryS=mid-90*sc,exitS=mid+115*sc,q=at(entryS),t=tan(entryS,55),nx=-t.y,ny=t.x,side=i%2?-1:1,x=q.x-nx*side*(outer-R-10),y=q.y-ny*side*(outer-R-10),join=at(exitS),jt=tan(exitS,50);let lower=[];for(let k=0;k<=20;k++){let u=k/20,e=u*u*(3-2*u);lower.push({x:x+(join.x-x)*e,y:y+(join.y-y)*e,s:exitS+u*95})}funnels.push({id:i,mid,entryS,exitS,x,y,outer,hole,depth,side,lower,jt})});c.g.forEach((fr,i)=>{let s=L*fr;if(funnels.some(f=>s>f.entryS-90&&s<f.exitS+120))return;let q=at(s),t=tan(s,50),nx=-t.y,ny=t.x,side=i%2?1:-1;pegs.push({x:q.x+nx*TRACK_HALF*side,y:q.y+ny*TRACK_HALF*side,r:8,s})});let xs=path.map(p=>p.x),ys=path.map(p=>p.y);funnels.forEach(f=>{xs.push(f.x-f.outer,f.x+f.outer);ys.push(f.y-f.outer,f.y+f.outer)});bounds={minX:Math.min(...xs)-150,maxX:Math.max(...xs)+150,minY:Math.min(...ys)-150,maxY:Math.max(...ys)+150}}
function contain(b){if(b.funnel||b.lower)return;let n=nearest(b),lim=TRACK_HALF-R-3,lat=(b.x-n.x)*n.nx+(b.y-n.y)*n.ny;if(Math.abs(lat)>lim){let side=Math.sign(lat)||1;b.x=n.x+n.nx*lim*side;b.y=n.y+n.ny*lim*side;let vn=b.vx*n.nx+b.vy*n.ny;if(vn*side>0){b.vx-=(1+WALL)*vn*n.nx;b.vy-=(1+WALL)*vn*n.ny}}b.s=n.s;return n}
function pegHit(b,p){if(b.funnel||b.lower||Math.abs(b.s-p.s)>220)return;let dx=b.x-p.x,dy=b.y-p.y,d=Math.hypot(dx,dy),m=R+p.r;if(d>=m)return;if(d<.001){dx=1;dy=0;d=1}let nx=dx/d,ny=dy/d;b.x+=nx*(m-d);b.y+=ny*(m-d);let vn=b.vx*nx+b.vy*ny;if(vn<0){b.vx-=(1+PEG)*vn*nx;b.vy-=(1+PEG)*vn*ny}}
function audioOn(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}
function clink(v,k){if(!audio)return;let n=audio.currentTime,l=lastClink.get(k)||-1;if(n-l<.05)return;lastClink.set(k,n);let g=audio.createGain(),a=audio.createOscillator(),c=audio.createOscillator();g.gain.setValueAtTime(clamp(v/420,.012,.08),n);g.gain.exponentialRampToValueAtTime(.0001,n+.055);a.frequency.value=1450+rnd(-100,100);c.frequency.value=2300+rnd(-150,150);a.connect(g);c.connect(g);g.connect(audio.destination);a.start(n);c.start(n);a.stop(n+.06);c.stop(n+.055)}
function ballsHit(a,b){let same=a.funnel&&b.funnel&&a.funnel.id===b.funnel.id;if((a.funnel||b.funnel)&&!same)return;if(!same&&Math.abs(a.s-b.s)>140)return;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>=R*2)return;if(d<.001){dx=1;dy=0;d=1}let nx=dx/d,ny=dy/d,p=R*2-d;a.x-=nx*p*.5;a.y-=ny*p*.5;b.x+=nx*p*.5;b.y+=ny*p*.5;let rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel>=0)return;let j=-(1+BALL)*rel*.5;a.vx-=j*nx;a.vy-=j*ny;b.vx+=j*nx;b.vy+=j*ny;clink(-rel,[a.id,b.id].sort().join('-'))}
function enter(b,f){let q=at(f.entryS),t=tan(f.entryS,45),nx=-t.y,ny=t.x,lane=clamp(((b.x-q.x)*nx+(b.y-q.y)*ny)/(TRACK_HALF-R),-1,1),base=Math.atan2(q.y-f.y,q.x-f.x),ang=base+lane*.18,r=f.outer-R-2;b.x=f.x+Math.cos(ang)*r;b.y=f.y+Math.sin(ang)*r;let dx=b.x-f.x,dy=b.y-f.y,d=Math.hypot(dx,dy)||1,rx=dx/d,ry=dy/d,out=b.vx*rx+b.vy*ry;if(out>0){b.vx-=out*rx;b.vy-=out*ry}let sp=Math.max(110,Math.hypot(b.vx,b.vy));if(Math.hypot(b.vx,b.vy)<sp*.45){let tx=-ry*f.side,ty=rx*f.side;b.vx+=tx*sp*.55;b.vy+=ty*sp*.55}b.funnel={id:f.id,f};b.s=f.entryS}
function funnelStep(b,dt){let f=b.funnel.f,dx=b.x-f.x,dy=b.y-f.y,d=Math.hypot(dx,dy)||1,u=clamp(1-d/f.outer,0,1),k=22+34*u*u;b.vx-=dx*k*dt;b.vy-=dy*k*dt;let damp=Math.exp(-.095*dt);b.vx*=damp;b.vy*=damp;b.x+=b.vx*dt;b.y+=b.vy*dt;dx=b.x-f.x;dy=b.y-f.y;d=Math.hypot(dx,dy)||1;let rx=dx/d,ry=dy/d,rim=f.outer-R;if(d>rim){let p=d-rim;b.x-=rx*p;b.y-=ry*p;let vn=b.vx*rx+b.vy*ry;if(vn>0){b.vx-=1.72*vn*rx;b.vy-=1.72*vn*ry}}u=clamp(1-d/f.outer,0,1);b.s=f.entryS+u*(f.exitS-f.entryS)*.9;if(d<f.hole+R*.3){b.funnel=null;b.lower={f,u:0};b.x=f.x;b.y=f.y;b.vx=0;b.vy=0;b.used.add(f.id);b.s=f.exitS}}
function lowerStep(b,dt){let f=b.lower.f,before=b.lower.u,sp=.95*dt,bnew=clamp(before+sp,0,1),idx=Math.min(f.lower.length-2,Math.floor(bnew*(f.lower.length-1))),u=bnew*(f.lower.length-1)-idx,a=f.lower[idx],c=f.lower[idx+1];b.x=a.x+(c.x-a.x)*u;b.y=a.y+(c.y-a.y)*u;b.lower.u=bnew;b.s=f.exitS+bnew*95;if(bnew>=1){let q=at(f.exitS+100),t=tan(f.exitS+100,50);b.x=q.x;b.y=q.y;b.vx=t.x*175;b.vy=t.y*175;b.s=f.exitS+100;b.lower=null;contain(b)}}
function step(dt,elapsed){let drag=Math.exp(-AIR*dt);for(let b of balls){if(b.finished)continue;if(b.funnel)funnelStep(b,dt);else if(b.lower)lowerStep(b,dt);else{let before=b.s,n=nearest(b);b.s=n.s;b.vx+=n.tx*GRAVITY*dt;b.vy+=n.ty*GRAVITY*dt;b.vx*=drag;b.vy*=drag;b.x+=b.vx*dt;b.y+=b.vy*dt;contain(b);for(let p of pegs)pegHit(b,p);for(let f of funnels)if(!b.used.has(f.id)&&before<f.entryS&&b.s>=f.entryS){enter(b,f);break}}let sp=Math.hypot(b.vx,b.vy);b.omega+=(sp/R-b.omega)*Math.min(1,dt*5);b.angle+=b.omega*dt}for(let p=0;p<3;p++)for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++)if(!balls[i].finished&&!balls[j].finished)ballsHit(balls[i],balls[j]);for(let i=0;i<balls.length;i++){let b=balls[i];if(b.finished)continue;if(b.s>=L-58){b.finished=true;b.finish=elapsed;finish.push(i);continue}if(b.s>b.lastS+30){b.lastS=b.s;b.lastAt=elapsed}else if(elapsed-b.lastAt>STALL&&Math.hypot(b.vx,b.vy)<30&&!b.funnel&&!b.lower){b.finished=true;b.dnf=true;b.finish=elapsed}}let active=balls.filter(b=>!b.finished).sort((a,b)=>b.s-a.s);active.forEach((b,k)=>b.rank=finish.length+k+1);hudUpdate();if(balls.every(b=>b.finished))endRace()}
function camera(){let active=balls.filter(b=>!b.finished);if(!active.length)return;let lead=active.reduce((a,b)=>b.s>a.s?b:a),near=active.filter(b=>lead.s-b.s<500),x=0,y=0,w=0;for(let b of near){let ww=b===lead?3:1;x+=b.x*ww;y+=b.y*ww;w+=ww}x/=w;y/=w;let t,z,h;if(lead.funnel){let f=lead.funnel.f;t=tan(f.entryS,80);x=f.x;y=f.y;z=zBefore(f);h=285}else if(lead.lower){let f=lead.lower.f;t=f.jt;z=zBefore(f)+f.depth;h=255}else{t=tan(lead.s,75);z=zAt(lead.s);h=240}let tx=x-t.x*300,ty=y-t.y*300,a=Math.atan2(t.y,t.x);camX+=(tx-camX)*.08;camY+=(ty-camY)*.08;camH+=(h-camH)*.07;camZ+=(z-camZ)*.1;let da=((a-camA+Math.PI*3)%(Math.PI*2))-Math.PI;camA+=clamp(da,-.06,.06);camS+=(lead.s-camS)*.08}
function proj(x,y,z=0){let fx=Math.cos(camA),fy=Math.sin(camA),rx=-fy,ry=fx,dx=x-camX,dy=y-camY,f=dx*fx+dy*fy,l=dx*rx+dy*ry,d=Math.max(30,f+165),fo=H*.79,s=fo/d;return{x:W*.5+l*s,y:H*.18+(camH+(z-camZ))*s,s,vis:f>-150&&f<1450}}
function trackRange(s0,s1,zOverride=null){let pts=path.filter(p=>p.s>=s0&&p.s<=s1);if(pts.length<2)return;let Ls=[],Rs=[];for(let p of pts){let t=tan(p.s,38),nx=-t.y,ny=t.x,z=zOverride===null?zAt(p.s):zOverride;Ls.push(proj(p.x+nx*TRACK_HALF,p.y+ny*TRACK_HALF,z));Rs.push(proj(p.x-nx*TRACK_HALF,p.y-ny*TRACK_HALF,z))}ctx.beginPath();ctx.moveTo(Ls[0].x,Ls[0].y);Ls.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));for(let i=Rs.length-1;i>=0;i--)ctx.lineTo(Rs[i].x,Rs[i].y);ctx.closePath();ctx.fillStyle='#273047';ctx.fill();for(let e of [Ls,Rs]){ctx.beginPath();ctx.moveTo(e[0].x,e[0].y);e.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.strokeStyle='#aeb9cc';ctx.lineWidth=7;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();ctx.strokeStyle='#53617a';ctx.lineWidth=3;ctx.stroke()}}
function lowerTrack(f){let z=zBefore(f)+f.depth,pts=f.lower,Ls=[],Rs=[];for(let i=0;i<pts.length;i++){let a=pts[Math.max(0,i-1)],b=pts[Math.min(pts.length-1,i+1)],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1,nx=-dy/l,ny=dx/l;Ls.push(proj(pts[i].x+nx*TRACK_HALF,pts[i].y+ny*TRACK_HALF,z));Rs.push(proj(pts[i].x-nx*TRACK_HALF,pts[i].y-ny*TRACK_HALF,z))}ctx.beginPath();ctx.moveTo(Ls[0].x,Ls[0].y);Ls.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));for(let i=Rs.length-1;i>=0;i--)ctx.lineTo(Rs[i].x,Rs[i].y);ctx.closePath();ctx.fillStyle='#20283a';ctx.fill();for(let e of [Ls,Rs]){ctx.beginPath();ctx.moveTo(e[0].x,e[0].y);e.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.strokeStyle='#9eabc0';ctx.lineWidth=6;ctx.stroke()}}
function funnelDraw(f){let base=zBefore(f),rings=22,steps=72,rr=[];for(let j=0;j<=rings;j++){let u=j/rings,r=f.outer*(1-u*.82),z=base+f.depth*Math.pow(u,1.4),a=[];for(let i=0;i<steps;i++){let ang=i/steps*Math.PI*2;a.push(proj(f.x+Math.cos(ang)*r,f.y+Math.sin(ang)*r,z))}rr.push(a)}for(let j=0;j<rings;j++){let u=(j+.5)/rings,q=Math.round(184-90*Math.pow(u,.8)),fill=`rgb(${q},${q+7},${Math.min(214,q+17)})`;for(let i=0;i<steps;i++){let n=(i+1)%steps,a=rr[j][i],b=rr[j][n],c=rr[j+1][n],d=rr[j+1][i];ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.closePath();ctx.fillStyle=fill;ctx.fill()}}let rim=rr[0];ctx.beginPath();ctx.moveTo(rim[0].x,rim[0].y);rim.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.closePath();ctx.strokeStyle='#e4e9f1';ctx.lineWidth=3;ctx.stroke();let h=[];for(let i=0;i<steps;i++){let a=i/steps*Math.PI*2;h.push(proj(f.x+Math.cos(a)*f.hole,f.y+Math.sin(a)*f.hole,base+f.depth))}ctx.beginPath();ctx.moveTo(h[0].x,h[0].y);h.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.closePath();ctx.fillStyle='#040609';ctx.fill()}
function finishDraw(){let s=L-55,q=at(s),t=tan(s,45),nx=-t.y,ny=t.x,z=zAt(s),a=proj(q.x+nx*(TRACK_HALF-7),q.y+ny*(TRACK_HALF-7),z),b=proj(q.x-nx*(TRACK_HALF-7),q.y-ny*(TRACK_HALF-7),z);for(let i=0;i<12;i++){let u=i/12,v=(i+1)/12;ctx.strokeStyle=i%2?'#fff':'#111';ctx.lineWidth=Math.max(5,10*(a.s+b.s)*.5);ctx.beginPath();ctx.moveTo(a.x+(b.x-a.x)*u,a.y+(b.y-a.y)*u);ctx.lineTo(a.x+(b.x-a.x)*v,a.y+(b.y-a.y)*v);ctx.stroke()}}
function courseDraw(){ctx.clearRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#17223e');g.addColorStop(1,'#080d18');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);camera();let a=Math.max(0,camS-500),b=Math.min(L,camS+1450),vis=funnels.filter(f=>f.exitS>a&&f.entryS<b).sort((x,y)=>x.entryS-y.entryS),cur=a;for(let f of vis){if(f.entryS>cur)trackRange(cur,f.entryS);cur=Math.max(cur,f.exitS)}if(cur<b)trackRange(cur,b);for(let f of vis){lowerTrack(f);funnelDraw(f)}for(let p of pegs){if(Math.abs(p.s-camS)>1100)continue;let q=proj(p.x,p.y,zAt(p.s)),r=Math.max(3,p.r*q.s);ctx.fillStyle='#d4a13d';ctx.beginPath();ctx.arc(q.x,q.y,r,0,Math.PI*2);ctx.fill()}finishDraw()}
function ballDraw(b){let z=zAt(b.s);if(b.funnel){let f=b.funnel.f,d=Math.hypot(b.x-f.x,b.y-f.y),u=clamp(1-d/f.outer,0,1);z=zBefore(f)+f.depth*Math.pow(u,1.4)}else if(b.lower)z=zBefore(b.lower.f)+b.lower.f.depth;let p=proj(b.x,b.y,z);if(!p.vis)return;let r=Math.max(4,R*p.s*1.25);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(b.angle);let g=ctx.createRadialGradient(-r*.35,-r*.4,2,0,0,r);g.addColorStop(0,'#fff');g.addColorStop(.18,b.color);g.addColorStop(1,'#111');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffffff90';ctx.lineWidth=Math.max(1.5,r*.12);ctx.beginPath();ctx.arc(0,0,r*.6,-1.2,1.15);ctx.stroke();ctx.restore()}
function minimap(){mctx.clearRect(0,0,MW,MH);mctx.fillStyle='#090e1b';mctx.fillRect(0,0,MW,MH);let bw=bounds.maxX-bounds.minX,bh=bounds.maxY-bounds.minY,s=Math.min((MW-18)/bw,(MH-18)/bh),ox=(MW-bw*s)/2-bounds.minX*s,oy=(MH-bh*s)/2-bounds.minY*s;mctx.beginPath();path.forEach((p,i)=>i?mctx.lineTo(ox+p.x*s,oy+p.y*s):mctx.moveTo(ox+p.x*s,oy+p.y*s));mctx.strokeStyle='#697791';mctx.lineWidth=Math.max(3,TRACK_HALF*2*s);mctx.stroke();mctx.strokeStyle='#242c40';mctx.lineWidth=Math.max(2,(TRACK_HALF*2-18)*s);mctx.stroke();funnels.forEach(f=>{mctx.fillStyle='#aab5c650';mctx.beginPath();mctx.arc(ox+f.x*s,oy+f.y*s,Math.max(3,f.outer*s),0,Math.PI*2);mctx.fill()});balls.forEach(b=>{mctx.fillStyle=b.color;mctx.beginPath();mctx.arc(ox+b.x*s,oy+b.y*s,4,0,Math.PI*2);mctx.fill();mctx.strokeStyle='#fff';mctx.lineWidth=1;mctx.stroke()})}
const ord=n=>n===1?'1st':n===2?'2nd':n===3?'3rd':'4th';
function hudMake(){hud.innerHTML='';COLORS.forEach((m,i)=>{let r=document.createElement('div');r.className='row';r.innerHTML=`<span class="dot" style="background:${m[1]}"></span><span class="name">${m[0]}</span><span class="place" id="p${i}">${i+1}</span>`;hud.appendChild(r)})}
function hudUpdate(){balls.forEach((b,i)=>{let e=document.getElementById('p'+i),r=e?.closest('.row');if(!e)return;r?.classList.toggle('finished',b.finished&&!b.dnf);r?.classList.toggle('dnf',b.dnf);e.textContent=b.dnf?'DNF':b.finished?`FINISHED • ${ord(finish.indexOf(i)+1)}`:ord(b.rank)})}
function resetBalls(){finish=[];lastClink.clear();let q=at(45),t=tan(45,45),nx=-t.y,ny=t.x;balls=COLORS.map((m,i)=>({id:i,name:m[0],color:m[1],x:q.x+nx*(i-1.5)*38,y:q.y+ny*(i-1.5)*38,vx:0,vy:0,angle:rnd(0,Math.PI*2),omega:0,finished:false,dnf:false,finish:0,rank:i+1,s:45,lastS:45,lastAt:0,used:new Set(),funnel:null,lower:null}));camX=q.x-t.x*290;camY=q.y-t.y*290;camA=Math.atan2(t.y,t.x);camS=45;camH=245;camZ=0;timerEl.textContent='00.0';hudUpdate();draw()}
function resize(){let r=stage.getBoundingClientRect();W=Math.max(320,Math.floor(r.width));H=Math.max(360,Math.floor(r.height));DPR=Math.min(devicePixelRatio||1,2);game.width=W*DPR;game.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0);let mr=map.getBoundingClientRect();MW=Math.max(80,Math.floor(mr.width));MH=Math.max(100,Math.floor(mr.height));MDPR=Math.min(devicePixelRatio||1,2);map.width=MW*MDPR;map.height=MH*MDPR;mctx.setTransform(MDPR,0,0,MDPR,0,0);draw()}
function draw(){if(!balls.length)return;courseDraw();[...balls].sort((a,b)=>a.s-b.s).forEach(ballDraw);minimap()}
function frame(now){if(state!=='racing')return;let elapsed=(now-start)/1000;timerEl.textContent=elapsed.toFixed(1).padStart(4,'0');let dt=Math.min(.03,(now-last)/1000||.016);last=now;for(let i=0;i<8;i++)step(dt/8,elapsed);draw();if(state==='racing')raf=requestAnimationFrame(frame)}
function startCard(){overlay.style.display='flex';overlay.innerHTML=`<div class="card courseCard"><h2>Choose a Course</h2><div class="courseGrid">${COURSES.map((c,i)=>`<button class="courseChoice ${i===course?'selected':''}" data-course="${i}"><strong>${c.name}</strong><span>${c.blurb}</span></button>`).join('')}</div><button id="startBtn">START RACE</button></div>`;overlay.querySelectorAll('.courseChoice').forEach(b=>b.addEventListener('click',()=>{course=Number(b.dataset.course);build();resetBalls();startCard()}));document.getElementById('startBtn').onclick=()=>{audioOn();startRace()}}
function resetRace(){token++;cancelAnimationFrame(raf);state='idle';build();resetBalls();startCard()}
async function startRace(){if(state==='countdown'||state==='racing')return;let tk=++token;resetBalls();state='countdown';overlay.style.display='flex';for(let n=3;n>=1;n--){if(tk!==token)return;overlay.innerHTML=`<div class="countdown">${n}</div>`;await new Promise(r=>setTimeout(r,650))}if(tk!==token)return;overlay.innerHTML='<div class="countdown">GO!</div>';await new Promise(r=>setTimeout(r,380));if(tk!==token)return;overlay.style.display='none';state='racing';start=performance.now();last=start;raf=requestAnimationFrame(frame)}
function endRace(){state='done';cancelAnimationFrame(raf);draw();let wi=finish[0],win=wi!==undefined?balls[wi]:null,ft=Math.max(...balls.map(b=>b.finish||0)),dnf=balls.filter(b=>b.dnf).length;timerEl.textContent=ft.toFixed(1);overlay.style.display='flex';overlay.innerHTML=`<div class="card"><h2>${win?`<span class="winner">${win.name}</span> Wins!`:'Race Over'}</h2><p>${COURSES[course].name}<br>${win?`Winning time: <strong>${win.finish.toFixed(1)}s</strong><br>`:''}${dnf?`${dnf} marble${dnf===1?'':'s'} recorded a DNF.`:'All four marbles finished.'}</p><button id="againBtn">RACE AGAIN</button></div>`;document.getElementById('againBtn').onclick=startCard}
document.getElementById('resetBtn').onclick=resetRace;addEventListener('resize',resize);build();hudMake();resetBalls();startCard();resize();
})();